name: Fetch CryptoCompare m15

on:
  schedule:
    - cron: "*/5 * * * *"   # chạy mỗi 5 phút
  workflow_dispatch:         # cho phép Run thủ công

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci || npm i

      - name: Fetch & build data
        env:
          CC_KEY: ${{ secrets.CRYPTOCOMPARE_KEY }}
        run: node scripts/fetch-cc.js

      - name: Commit & push if changed
        run: |
          if [[ -n "$(git status --porcelain data)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add data/*.json
            git commit -m "data: update m15 $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push
          else
            echo "No changes to commit."
          fi
